# Generated by Django 5.1.3 on 2024-11-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comics/"),
        ),
    ]
