# Generated by Django 5.1.3 on 2024-11-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0003_remove_comic_image_user_phone_number_comicimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="image",
            field=models.ImageField(default="def.jpg", upload_to="comics/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ComicImage",
        ),
    ]
